### PR TITLE
Add blog post about GitLab CI with custom tools in containers

### PR DESCRIPTION
**Pull request by XCompWiz**

### CODE REVIEW

**Comment by rubyrat** [comment]
This is the correct image
supporting-gitlab-ci-custom-tools-in-containers

**Comment by rubyrat** [comment]
Looks like something failed in the build.

**Comment by XCompWiz** [comment]
> Looks like something failed in the build.

It partially failed; seems to be some follow-up step. I think the blog was still successfully on preview.
I've re-run he failed job. I don't think it was anything to do with the code, but just a timeout issue.

**Comment by XCompWiz** [comment]
Updated the image

**Comment by rubyrat** [comment]
LGTM!

**Pull request merged**
